#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build.py — 将 data/*.json 合成为 assets/js/data.js，供 index.html 加载。
职责：
  1. 读取 models.json / skills.json / tools.json
  2. 价格 USD -> CNY 换算（按 meta 汇率）
  3. 生成带时间戳的 meta
  4. 输出 window.RADAR_DATA = {...} 到 assets/js/data.js
  5. 数据完整性校验（无来源分数告警）
"""
import json
import sys
import datetime
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE, "data")
OUT_DIR = os.path.join(BASE, "assets", "js")


def load(name):
    p = os.path.join(DATA_DIR, name)
    with open(p, encoding="utf-8") as f:
        return json.load(f)


def main():
    models = load("models.json")
    skills = load("skills.json")
    tools = load("tools.json")

    fx = models["_meta"].get("fx_usd_cny", 7.0)
    fx_date = models["_meta"].get("fx_date", "?")

    # 价格换算 + 校验
    warnings = []
    for m in models["models"]:
        m["price_cny"] = {
            "in": round(m["price"]["in"] * fx, 2),
            "out": round(m["price"]["out"] * fx, 2),
        }
        # 校验：任何有分数但无 src 的维度
        for k, v in m["abilities"].items():
            if v.get("score") is not None and not v.get("src"):
                warnings.append(f"{m['name']}.{k} 有分数但无来源")

    now = datetime.datetime.utcnow()
    generated = now.strftime("%Y-%m-%d %H:%M UTC")

    payload = {
        "meta": {
            "generated": generated,
            "fx_usd_cny": fx,
            "fx_date": fx_date,
            "model_count": len(models["models"]),
            "skill_count": len(skills["skills"]),
            "tool_count": len(tools["tools"]),
            "github_updated": skills["_meta"].get("updated") or tools["_meta"].get("updated") or "?",
            "sources": models["_meta"],
        },
        "models": models["models"],
        "skills": skills["skills"],
        "tools": tools["tools"],
    }

    os.makedirs(OUT_DIR, exist_ok=True)
    out = os.path.join(OUT_DIR, "data.js")
    js = "/* AUTO-GENERATED by build.py — DO NOT EDIT */\n"
    js += "window.RADAR_DATA = " + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n"
    with open(out, "w", encoding="utf-8") as f:
        f.write(js)

    print(f"[OK] data.js 生成: {out}")
    print(f"[OK] 模型 {payload['meta']['model_count']} | skills {payload['meta']['skill_count']} | tools {payload['meta']['tool_count']}")
    print(f"[OK] 汇率 1 USD = {fx} CNY ({fx_date}) | 生成时间 {generated}")
    if warnings:
        print("[WARN] 数据校验告警:")
        for w in warnings:
            print("  -", w)
        sys.exit(1)
    else:
        print("[OK] 数据完整性校验通过（无'无来源分数'）")


if __name__ == "__main__":
    main()
